@restaurantId=a1eb96d8-3cd5-4b20-908c-b4ce6853eac4

### Register Restaurant
POST http://localhost:8000/admin/restaurants
Content-Type: application/json

{
    "name": "La Boucherie de Damien",
    "ownerName": "Jean-Pierre",
    "foodTypes": ["Pizza", "Burger", "French"],
    "postalcode": "75001",
    "address": "Rue de la paix",
    "phone": "0612345678",
    "email": "damien@gmail.com",
    "password": "123456"
}

### Get Restaurants
GET http://localhost:8000/admin/restaurants

### Get Restaurant By ID
GET http://localhost:8000/admin/restaurants/{{restaurantId}}




