@restaurantId=1fc152e7-b657-4ea6-b7e1-2a6f5282f756
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFmYzE1MmU3LWI2NTctNGVhNi1iN2UxLTJhNmY1MjgyZjc1NiIsIm5hbWUiOiJMZSBQZXRpdCBCaXN0cm8iLCJvd25lck5hbWUiOiJJc2FiZWxsZSBEdXBvbnQiLCJlbWFpbCI6ImxlcGV0aXRiaXN0cm9AZ21haWwuY29tIiwiZm9vZFR5cGVzIjpbIkZyZW5jaCIsIlNlYWZvb2QiXSwiaWF0IjoxNzY4MzIxMTY2LCJleHAiOjE3Njg0MDc1NjZ9.0QrLMJQkuqAoBeAfehx674u_AYCyt6FRE2yKSa2SkNI

### Register Restaurant
POST http://localhost:8000/api/v1/admin/restaurants
Content-Type: application/json

{
    "name": "La Boucherie de Damien",
    "ownerName": "Jean-Pierre",
    "foodTypes": ["Pizza", "Burger", "French"],
    "postalcode": "75001",
    "address": "Rue de la paix",
    "phone": "0612345678",
    "email": "damien@gmail.com",
    "password": "123456"
}

### Get Restaurants
GET http://localhost:8000/api/v1/admin/restaurants

### Get Restaurant By ID
GET http://localhost:8000/api/v1/admin/restaurants/{{restaurantId}}

### Login
POST http://localhost:8000/api/v1/restaurant/login
Content-Type: application/json

{
    "email": "lepetitbistro@gmail.com",
    "password": "qwerty"
}


### Get Profile
GET http://localhost:8000/api/v1/restaurant/profile
Authorization: Bearer {{token}}

### Update profile
PATCH http://localhost:8000/api/v1/restaurant/profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Le Petit Bistro",
    "ownerName": "Damien",
    "foodTypes": ["French", "Seafood", "Italian"],
    "address": "10 Rue de la Roquette",
    "phone": "01 45 67 89 10"
}

### Update Service availability
PATCH http://localhost:8000/api/v1/restaurant/profile/service-available
Authorization: Bearer {{token}}


### Update Cover Images
PATCH http://localhost:8000/api/v1/restaurant/profile/cover-images
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=limite

--limite
Content-Disposition: form-data; name="images"; filename="restaurant_1.jpg"
Content-Type: image/jpeg

< ./images/tests/restaurant_1.jpg

--limite
Content-Disposition: form-data; name="images"; filename="restaurant_2.jpg"
Content-Type: image/jpeg

< ./images/tests/restaurant_2.jpg
--limite--


### Add Food
POST http://localhost:8000/api/v1/restaurant/foods
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=limite

--limite
Content-Dispostion: form-data; name="data"
Content-Type: application/json

{
    "name": "Pates",
    "description": "Des pates à la crème",
    "category": "pates",
    "foodType": "pates",
    "readyTime": 15,
    "price": 15.90
}

--limite
Content-Disposition: form-data; name="images"; filename="pates.jpg"
Content-Type: image/jpeg

< ./images/tests/pates.jpg
--limite--


### Get Foods
GET http://localhost:8000/api/v1/shopping/available-foods/75010

### Shopping: Get Top restaurants
GET http://localhost:8000/api/v1/shopping/top-restaurants/75010

### Shopping: Get foods in 30 mins
GET http://localhost:8000/api/v1/shopping/foods-in-mins/75001

### Shopping: Search foods
GET http://localhost:8000/api/v1/shopping/search-foods/75010?search=burger